### PR TITLE
fix WSS close

### PR DESCRIPTION
**Pull request by kukies007**
Closing a WSS connection breaks communication on a reused socket handle.
SSL_shutdown() should be called before closing socket to avoid TLS close notify to be send on a reused socket.

### CODE REVIEW

**Comment by kukies007** [comment]
Can someone explain why the checks have failed? I could not see any relations to my PR.

**Comment by kukies007** [comment]
Seems like all current PRs fail on the same unit test.

**Comment by andywolk** [comment]
Please never mind that test.

**Comment by jalsot** [comment]
It seems to be approved, what needs to be done to been merged? :)
It seems this fix gives more wss stability at our end too (unfortunately only a very small experience).

**Comment by andywolk** [comment]
This PR does not look correct. Closed in favor of https://github.com/freeswitch/sofia-sip/pull/175

**Pull request closed without merging**
