### PR TITLE
multiple identity headers

### PR DESCRIPTION
**Pull request by hnimminh**
From rfc8224 https://datatracker.ietf.org/doc/html/rfc8224#page-7
Note that unlike the prior specification in [RFC4474], the Identity header field is now allowed to appear more than one time in a SIP request.

This one serve for: https://github.com/signalwire/freeswitch/pull/1747

### CODE REVIEW

**Comment by hnimminh** [comment]
@andywolk can you take a look on this PR.
Error fail in Unit Test seem not related to my change. 
Thanks so much!

**Review by andywolk — APPROVED** [review]

**Comment by andywolk** [comment]
Please rebase the branch against origin/master

**Comment by hnimminh** [comment]
Thanks @andywolk done!

**Comment by hnimminh** [comment]
What can I do to merge this PR to master, can advice @andywolk ?

**Pull request merged**
